<?php namespace Aifang\Web;

class Resource {
    private static $js = array();
    private static $css = array();

    public static function addJS($data = array())
    {
        if (! empty($data)) {
            self::$js = array_unique(array_merge(self::$js, $data));
        }
    }

    public static function addCSS($data = array())
    {
        if (! empty($data)) {
            self::$css = array_unique(array_merge(self::$css, $data));
        }
    }

    public static function getJS()
    {
        $import_js = '[';
        $len = count(self::$js) - 1;
        foreach(self::$js as $i => $js) {
            $import_js .= "'" . $js . "'" . (($i < $len) ? ', ' : '');
        }
        $import_js .= ']';

        return $import_js;
    }

    public static function getCSS()
    {
        $import_css = "";
        foreach(self::$css as $css) {
            $import_css .= "@import url('" . $css . ".css');" . "\n";
        }
        return $import_css;
    }

    public static function autoGenerate($file_js, $file_css)
    {
        if ($file_js) {
            $file_js = public_path() . "/www/" . $file_js . '.js';
            $js_content = self::_autoGenerateJsContent();
            file_put_contents($file_js, $js_content);
        }

        if ($file_css) {
            $file_css = public_path() . "/www/" . $file_css . '.css';
            $css_content = self::_autoGenerateCssContent();
            file_put_contents($file_css, $css_content);
        }

    }

    private static function _autoGenerateJsContent()
    {
        $content = "//This code is generated by PHP.\n";
        $content .= "//Load common code that includes config, then load the app logic for this page.\n";
        $content .= "require(['./common'], function (common) {\n";
        $content .= "   require(" . self::getJS() . ");\n";
        $content .= "});";

        return $content;
    }

    private static function _autoGenerateCssContent()
    {
        $content = "/* This code is generated by PHP. */\n";
        $content .= self::getCSS();

        return $content;
    }

}

